[build]
  base = "frontend/laboratory-frontend"
  command = "npm ci && npm run build"
  publish = "dist/laboratory-frontend/browser"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
