[build]
  base = "frontend/laboratory-frontend/"
  command = "npm install && npm run build"
  publish = "dist/laboratory-frontend"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200