[build]
  base = "frontend/laboratory-frontend/"
  command = "npm install && npm run build"
  publish = "frontend/laboratory-frontend/dist/laboratory-frontend"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true